<a href="https://colab.research.google.com/github/Irina-Batychko/Homework_10_Python_28_02_2023/blob/main/%D0%94%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BA_%D1%81%D0%B5%D0%BC%D0%B8%D0%BD%D0%B0%D1%80%D1%83_%E2%84%9610.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задача 44:**

---


В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего
из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без
get_dummies?

In [ ]:
import pandas as pd

import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  human
1  human
2  robot
3  robot
4  robot

In [ ]:
# 0 - robot
# 1 - human
data=pd.DataFrame(random.sample(['0', '1']*10, 20), columns={'whoAmI'})
data.head(20)

   whoAmI
0       0
1       1
2       0
3       1
4       1
5       0
6       0
7       1
8       1
9       1
10      0
11      1
12      0
13      0
14      0
15      1
16      1
17      0
18      0
19      1